url: https://denismcdonald.github.io
baseurl: /jekyll-from-scratch
repository: denismcdonald/jekyll-from-scratch

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      edit: "true"
      toc: "true"
  - scope:
      path: ""
    values:
      layout: "default"