url: https://denismcdonald.github.io
baseurl: 
repository: denismcdonald/blog

permalink: blog/:categories/:year/:month/:day/:title:output_ext
# was blog/:categories/:year/:month/:day/:title:output_ext

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      edit: "true"
      toc: "true"
      footer: "true"
  - scope:
      path: ""
    values:
      layout: "default"
      footer: "true"